---
services:
  immich-proxy:
    image: ghcr.io/tomleb/immich-proxy:release
    restart: unless-stopped
    ports:
    - 8080:8080
    environment:
    # Your actual immich instance (eg: can be localhost:<port>, etc)
    - IMMICH_SERVER_URL=https://demo.immich.app
    # Overrides the Host HTTP header with this
    - IMMICH_HOST=demo.immich.app
